---
title: "Cache GRTS Dataframes"
output:
  html_document: default
---


Import packages for building and cacheing out dataframes for CONUS, Alaska, Hawaii, Puerto Rico, Canada, and Mexico
```{r}
library(leaflet)
library(leaflet.extras)
library(rgdal)
library(sp)
library(raster)
library(tidyr)
library(plotly)
```

# CONUS
```{r}
CONUS     = readOGR('/users/kenns/projects/r/nabat/shinybatr/data/conus_mastersample_10km_attributed/')
# p = CONUS[CONUS$GRTS_ID %in% c(55478,2,5,90,15),]
p =  spTransform(CONUS, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
p

leaflet() %>% addTiles() %>% addPolygons(data = subset(p, GRTS_ID < 2000))

grts_ids = p$GRTS_ID
grts_centerpoints = paste(p$lat,p$long,sep=',')
grts_lat_lons =  p %>% fortify() %>% select(long,lat,order,id) 
grts_lat_lons$latlon = paste(grts_lat_lons$lat,grts_lat_lons$long,sep=',') 
grts_lat_lons = select(grts_lat_lons,latlon,order,id)
number_of_points = dim(grts_lat_lons)[1] / dim(p)[1]

grts_ids_df_version = rep(grts_ids, each = number_of_points)

inter_df = data.frame(GRTS_ID = grts_ids_df_version, latlon = grts_lat_lons$latlon, 
  id = grts_lat_lons$id, order= grts_lat_lons$order, stringsAsFactors = FALSE)
inter_df_1 = inter_df %>% group_by(GRTS_ID) %>% spread(order, latlon)
inter_df_1

final_df =  inter_df_1 %>% select(GRTS_ID, '2','4','6','8')
names(final_df)[2] = 'lowerleft'
names(final_df)[3] = 'upperleft'
names(final_df)[4] = 'upperright'
names(final_df)[5] = 'lowerright'
final_df$center = grts_centerpoints
final_df
write.csv(final_df, file = '/users/kenns/downloads/GRTS_coords_CONUS.csv')
```

# Hawaii
```{r}
Hawaii     = readOGR('/users/kenns/projects/r/nabat/shinybatr/data/HI_mastersample_5km_attributed/')
p = Hawaii
p =  spTransform(Hawaii, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
p

leaflet() %>% addTiles() %>% addPolygons(data = subset(p, GRTS_ID < 2000))

grts_ids = p$GRTS_ID
grts_centerpoints = paste(p$lat,p$long,sep=',')
grts_lat_lons =  p %>% fortify() %>% select(long,lat,order,id) 
grts_lat_lons$latlon = paste(grts_lat_lons$lat,grts_lat_lons$long,sep=',') 
grts_lat_lons = select(grts_lat_lons,latlon,order,id)
number_of_points = dim(grts_lat_lons)[1] / dim(p)[1]

grts_ids_df_version = rep(grts_ids, each = number_of_points)

inter_df = data.frame(GRTS_ID = grts_ids_df_version, latlon = grts_lat_lons$latlon, 
  id = grts_lat_lons$id, order= grts_lat_lons$order, stringsAsFactors = FALSE)
inter_df_1 = inter_df %>% group_by(GRTS_ID) %>% spread(order, latlon)
inter_df_1

final_df =  inter_df_1 %>% select(GRTS_ID, '1','2','3','4')
names(final_df)[2] = 'lowerleft'
names(final_df)[3] = 'upperleft'
names(final_df)[4] = 'upperright'
names(final_df)[5] = 'lowerright'
final_df$center = grts_centerpoints
final_df
write.csv(final_df, file = '/users/kenns/downloads/GRTS_coords_Hawaii.csv')

```

# ALASKA
```{r}
Alaska     = readOGR('/users/kenns/projects/r/nabat/shinybatr/data/AK_mastersample_10km_attributed/')
p = Alaska
p =  spTransform(Alaska, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
p

leaflet() %>% addTiles() %>% addPolygons(data = subset(p, GRTS_ID < 2000))

grts_ids = p$GRTS_ID
grts_centerpoints = paste(p$lat,p$long,sep=',')
grts_lat_lons =  p %>% fortify() %>% select(long,lat,order,id) 
grts_lat_lons$latlon = paste(grts_lat_lons$lat,grts_lat_lons$long,sep=',') 
grts_lat_lons = select(grts_lat_lons,latlon,order,id)
number_of_points = dim(grts_lat_lons)[1] / dim(p)[1]

grts_ids_df_version = rep(grts_ids, each = number_of_points)

inter_df = data.frame(GRTS_ID = grts_ids_df_version, latlon = grts_lat_lons$latlon, 
  id = grts_lat_lons$id, order= grts_lat_lons$order, stringsAsFactors = FALSE)
inter_df_1 = inter_df %>% group_by(GRTS_ID) %>% spread(order, latlon)
inter_df_1

final_df =  inter_df_1 %>% select(GRTS_ID, '2','4','6','8')
names(final_df)[2] = 'lowerleft'
names(final_df)[3] = 'upperleft'
names(final_df)[4] = 'upperright'
names(final_df)[5] = 'lowerright'
final_df$center = grts_centerpoints
final_df
write.csv(final_df, file = '/users/kenns/downloads/GRTS_coords_Alaska.csv')
```

# Puerto Rico
```{r}
Puerto_Rico     = readOGR('/users/kenns/projects/r/nabat/shinybatr/data/PR_mastersample_5km_attributed/')
p = Puerto_Rico
p =  spTransform(Puerto_Rico, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
p
leaflet() %>% addTiles() %>% addPolygons(data = p)


grts_ids = p$GRTS_ID
grts_centerpoints = paste(p$lat,p$long,sep=',')
grts_lat_lons =  p %>% fortify() %>% select(long,lat,order,id) 
grts_lat_lons$latlon = paste(grts_lat_lons$lat,grts_lat_lons$long,sep=',') 
grts_lat_lons = select(grts_lat_lons,latlon,order,id)
number_of_points = dim(grts_lat_lons)[1] / dim(p)[1]

grts_ids_df_version = rep(grts_ids, each = number_of_points)

inter_df = data.frame(GRTS_ID = grts_ids_df_version, latlon = grts_lat_lons$latlon, 
  id = grts_lat_lons$id, order= grts_lat_lons$order, stringsAsFactors = FALSE)
inter_df_1 = inter_df %>% group_by(GRTS_ID) %>% spread(order, latlon)
inter_df_1

final_df =  inter_df_1 %>% select(GRTS_ID, '1','2','3','4')
names(final_df)[2] = 'lowerleft'
names(final_df)[3] = 'upperleft'
names(final_df)[4] = 'upperright'
names(final_df)[5] = 'lowerright'
final_df$center = grts_centerpoints
final_df
write.csv(final_df, file = '/users/kenns/downloads/GRTS_coords_Puerto_Rico.csv')
```

# Mexico
```{r}
Mexico     = readOGR('/users/kenns/projects/r/nabat/shinybatr/data/Mex_mastersample_10km_attributed//')
p = Mexico
p =  spTransform(Mexico, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
p

leaflet() %>% addTiles() %>% addPolygons(data = subset(p, GRTS_ID < 2000))

grts_ids = p$GRTS_ID
grts_centerpoints = paste(p$lat,p$long,sep=',')
grts_lat_lons =  p %>% fortify() %>% select(long,lat,order,id) 
grts_lat_lons$latlon = paste(grts_lat_lons$lat,grts_lat_lons$long,sep=',') 
grts_lat_lons = select(grts_lat_lons,latlon,order,id)
number_of_points = dim(grts_lat_lons)[1] / dim(p)[1]

grts_ids_df_version = rep(grts_ids, each = number_of_points)

inter_df = data.frame(GRTS_ID = grts_ids_df_version, latlon = grts_lat_lons$latlon, 
  id = grts_lat_lons$id, order= grts_lat_lons$order, stringsAsFactors = FALSE)
inter_df_1 = inter_df %>% group_by(GRTS_ID) %>% spread(order, latlon)
inter_df_1

final_df =  inter_df_1 %>% select(GRTS_ID, '2','4','6','8')
names(final_df)[2] = 'lowerleft'
names(final_df)[3] = 'upperleft'
names(final_df)[4] = 'upperright'
names(final_df)[5] = 'lowerright'
final_df$center = grts_centerpoints
final_df
write.csv(final_df, file = '/users/kenns/downloads/GRTS_coords_Mexico.csv')
```

# Canada
```{r}
Canada     = readOGR('/users/kenns/projects/r/nabat/shinybatr/data/Can_mastersample_10km_attributed/')
p = Canada
p =  spTransform(Canada, CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))
p

leaflet() %>% addTiles() %>% addPolygons(data = subset(p, GRTS_ID < 2000))

grts_ids = p$GRTS_ID
grts_centerpoints = paste(p$lat,p$long,sep=',')
grts_lat_lons =  p %>% fortify() %>% select(long,lat,order,id) 
grts_lat_lons$latlon = paste(grts_lat_lons$lat,grts_lat_lons$long,sep=',') 
grts_lat_lons = select(grts_lat_lons,latlon,order,id)
number_of_points = dim(grts_lat_lons)[1] / dim(p)[1]

grts_ids_df_version = rep(grts_ids, each = number_of_points)

inter_df = data.frame(GRTS_ID = grts_ids_df_version, latlon = grts_lat_lons$latlon, 
  id = grts_lat_lons$id, order= grts_lat_lons$order, stringsAsFactors = FALSE)
inter_df_1 = inter_df %>% group_by(GRTS_ID) %>% spread(order, latlon)
inter_df_1

final_df =  inter_df_1 %>% select(GRTS_ID, '2','4','6','8')
names(final_df)[2] = 'lowerleft'
names(final_df)[3] = 'upperleft'
names(final_df)[4] = 'upperright'
names(final_df)[5] = 'lowerright'
final_df$center = grts_centerpoints
final_df
write.csv(final_df, file = '/users/kenns/downloads/GRTS_coords_Canada.csv')
```

