---
title: "Get Mobile Acoustic data"
output:
  html_document: default
---

## Explore your Mobile Acoustic NABat data using this Rmd example


### Get a token for NABat Database
```{r}
library(nabatr)
# Enter your NABat username here
username = 'NABat_Username'
token = get_nabat_gql_token(username)
token

# Note: if you leave run token = get_nabat_gql_token(),
#   it will prompt you for a username and then a password
```


### Get Project dataframe which contains all of your NABat projects in the NABat Database
```{r}
# Refresh token
token = get_refresh_token(token)
# Get your projects lookup table
project_df = get_projects(token)
# Display your projects lookup table
project_df
```


### Get all Mobile Acoustic Surveys within a single Project set with project_id
```{r}
# Refresh token
token = get_refresh_token(token)
# Fill in project id using the project_df lookup table
project_id = 000 # Set equal to one of your project ids

# Get survey dataframe 
ma_survey_df = get_ma_project_summary(token, 
                                      project_df, 
                                      project_id)
                                          
ma_proj_dates = unique(ma_survey_df$year)
# Display survey dataframe
ma_survey_df
```


### Get all Mobile Acoustic Survey wav file data.  Format: Mobile Acoustic Bulk Upload Template
```{r}
# Select Year for project (defaults to 1st available year)
year = ma_proj_dates[1]

# Refresh token
token = get_refresh_token(token)
# Get mobile acoustic bulk upload format dataframe
ma_bulk_df = get_ma_bulk_wavs(token,
                              ma_survey_df,
                              year)
# Display mobile acoustic bulk upload format dataframe
ma_bulk_df
```
